# Generated by Django 5.0.3 on 2024-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='media/certificates/pdf')),
                ('jpg_file', models.ImageField(upload_to='media/certificates/jpg')),
            ],
        ),
    ]
