# Generated by Django 5.0.3 on 2024-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_role',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='role_description',
            field=models.TextField(default='N/A'),
        ),
    ]
