# Generated by Django 5.0.3 on 2026-07-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projects_project_role_projects_role_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Roadmap', max_length=100)),
                ('horizontal_image', models.ImageField(upload_to='media/roadmap/')),
                ('vertical_image', models.ImageField(upload_to='media/roadmap/')),
            ],
        ),
    ]
